export const LOG_IN = 'LOG_IN'
export const LOGGED_IN = 'LOGGED_IN'
export const LOG_OUT = 'LOG_OUT'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const FECTH_INVESTIGATIONS = "FECTH_INVESTIGATIONS"
export const FECTH_INVESTIGATIONS_FULFILLED = "FECTH_INVESTIGATIONS_FULFILLED"
export const FECTH_INVESTIGATIONS_PENDING = "FECTH_INVESTIGATIONS_PENDING"
export const FECTH_INVESTIGATIONS_DOI = "FECTH_INVESTIGATIONS_DOI"
export const FECTH_INVESTIGATIONS_DOI_FULFILLED = "FECTH_INVESTIGATIONS_DOI_FULFILLED"
export const FECTH_INVESTIGATIONS_DOI_PENDING = "FECTH_INVESTIGATIONS_DOI_PENDING"

export const FECTH_DATASETS_BY_INVESTIGATION_ID = "FECTH_DATASETS_BY_INVESTIGATION_ID"
export const FECTH_DATASETS_BY_INVESTIGATION_ID_FULFILLED = "FECTH_DATASETS_BY_INVESTIGATION_ID_FULFILLED"
export const FECTH_DATASETS_BY_INVESTIGATION_ID_REJECTED = "FECTH_DATASETS_BY_INVESTIGATION_ID_REJECTED"

// for wallelog
export const CHANGE_PAGE = 'CHANGE_PAGE'  
